M48
; DRILL file {KiCad 7.0.0-da2b9df05c~163~ubuntu22.04.1} date Sun Feb 19 21:10:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-19T21:10:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~163~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X149.177Y-91.984
X149.177Y-96.484
T0
M30
